/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults, } from "@stencil/router";
import { Recipe, } from "./utils/interfaces";
export namespace Components {
    interface AppHome {
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
    interface RecipeAddForm {
    }
    interface RecipeCard {
        "recipe": Recipe;
    }
    interface RecipeList {
        "fetchRecipes": () => Promise<void>;
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLRecipeAddFormElement extends Components.RecipeAddForm, HTMLStencilElement {
    }
    var HTMLRecipeAddFormElement: {
        prototype: HTMLRecipeAddFormElement;
        new (): HTMLRecipeAddFormElement;
    };
    interface HTMLRecipeCardElement extends Components.RecipeCard, HTMLStencilElement {
    }
    var HTMLRecipeCardElement: {
        prototype: HTMLRecipeCardElement;
        new (): HTMLRecipeCardElement;
    };
    interface HTMLRecipeListElement extends Components.RecipeList, HTMLStencilElement {
    }
    var HTMLRecipeListElement: {
        prototype: HTMLRecipeListElement;
        new (): HTMLRecipeListElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "recipe-add-form": HTMLRecipeAddFormElement;
        "recipe-card": HTMLRecipeCardElement;
        "recipe-list": HTMLRecipeListElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface RecipeAddForm {
        "onRecipeAddRequest"?: (event: CustomEvent<any>) => void;
    }
    interface RecipeCard {
        "recipe"?: Recipe;
    }
    interface RecipeList {
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "recipe-add-form": RecipeAddForm;
        "recipe-card": RecipeCard;
        "recipe-list": RecipeList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "recipe-add-form": LocalJSX.RecipeAddForm & JSXBase.HTMLAttributes<HTMLRecipeAddFormElement>;
            "recipe-card": LocalJSX.RecipeCard & JSXBase.HTMLAttributes<HTMLRecipeCardElement>;
            "recipe-list": LocalJSX.RecipeList & JSXBase.HTMLAttributes<HTMLRecipeListElement>;
        }
    }
}
